CLASSIC_ROUTES_BLOCKS_COUNT = [1, 1]

CLASSIC_ROUTES_MODULES_USING = [
    ["somnia_claim_faucet"],
    [
        ["somnia_quick_swap_stt_to_usdc"],
        ["somnia_quick_swap_usdc_to_stt"],
    ],
]
