CLASSIC_ROUTES_BLOCKS_COUNT = [2, 2]


CLASSIC_ROUTES_MODULES_USING = [
    ["somnia_claim_faucet"],
    [
        ["somnia_follow_campaign"]
    ],
    [
        ["somnia_foru_campaign"]
    ],
    [
        ["somnia_yappers_campaign"]
    ]
]
