CLASSIC_ROUTES_BLOCKS_COUNT = [5, 5]


CLASSIC_ROUTES_MODULES_USING = [
    [
        ["somnia_mint_movinfinity_mask"]
    ],
    [
        ["somnia_mint_movinfinity_mask"]
    ],
    [
        ["somnia_mint_movinfinity_mask"]
    ],
    [
        ["somnia_mint_movinfinity_mask"]
    ],
    [
        ["somnia_mint_movinfinity_mask"]
    ],
]
