CLASSIC_ROUTES_BLOCKS_COUNT = [2, 5]

CLASSIC_ROUTES_MODULES_USING = [
    ["somnia_claim_faucet"],
    [
        ["somnia_quick_swap_stt_to_usdc"],
        ["somnia_quick_swap_usdc_to_stt"],
    ],
    [
        ["somnia_mint_nee"],
    ],
    [
        ["somnia_mint_shannon"],
    ],
    [
        ["somnia_mint_somni"],
    ],
    [
        ["somnia_mint_yappers"],
    ],
]
