CLASSIC_ROUTES_MODULES_USING = [
    ['eclipse_cex_withdraw_sol'],
    ['eclipse_refuel_gaszip'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_cex_deposit_sol'],
]
