CLASSIC_ROUTES_MODULES_USING = [
    ['eclipse_cex_withdraw_sol'],
    ['eclipse_refuel_gazzip'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_swap_sol_to_eth_orca'],
    ['eclipse_swap_eth_to_sol_orca'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_swap_sol_to_eth_orca'],
    ['eclipse_swap_eth_to_sol_orca'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_cex_deposit_sol'],
]
