CLASSIC_ROUTES_MODULES_USING = [
    ['withdraw_cex'],
    ['bridge_eth_to_sol_jumper'],
    ['eclipse_refuel_gaszip'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_swap_sol_to_eth_orca'],
    ['eclipse_swap_eth_to_sol_orca'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_swap_sol_to_eth_orca'],
    ['eclipse_swap_eth_to_sol_orca'],
    ['eclipse_bridge_sol_usenexus'],
    ['bridge_sol_to_eth_jumper'],
    ['deposit_cex'],
]
