CLASSIC_ROUTES_MODULES_USING = [
    ['withdraw_cex'],
    ['eclipse_bridge_relay_l1'],
    ['eclipse_mint_teth'],
]

CEX_NETWORKS = [2, 3, 6]                     # какие сети использовать для вывода с биржи (2 - Arbitrum, 3 - Optimism, 6 - Base)
CEX_WITHDRAW_AMOUNT = [0.007, 0.008]         # сумма вывода ETH в сети CEX_NETWORKS. Можно указывать % или кол-во

ECLIPSE_WETH_FEE_LIMITER = [0.004, 0.004]   # сумма ETH для использования под комиссию на бридж. Софт будет вычитать ее из суммы под врап ETH
ECLIPSE_WETH_BRIDGE_AMOUNT = ['100', '100'] # сумма WETH для бриджа через https://app.eclipse.xyz/mint-teth
ECLIPSE_WETH_SKIP_WRAP = false              # пропускать ли врап ETH, включайте, если у вас уже есть балансы в WETH

BRIDGE_RELAY_L2_NETWORK = ['Arbitrum', 'Optimism', 'Base'] # сети, которые используются для бриджа через Relay
BRIDGE_RELAY_AMOUNT = ['100', '100']         # сумма бриджа нативки между сетями через Relay
BRIDGE_RELAY_MAX_IMPACT = 7.0              # максимальная разница в % исходящей и входящей суммы, софт будет ждать данную разницу
