ABSTRACT_SWAP_COUNT = [1, 5] # количество свапов на https://www.abs.xyz/trade
ABSTRACT_SWAP_AMOUNT = ['10', '20'] # сумма свапов на https://www.abs.xyz/trade. Применяется только к ETH, обратно 100%

ABSTRACT_LINK_DISCORD = true # привязывать аккаунт Discord к профилю Abstract
ABSTRACT_LINK_TWITTER = true # привязывать аккаунт Twitter к профилю Abstract