#---------------------------------------------------ABSTRACT CONTROL----------------------------------------------------

ABSTRACT_SWAP_COUNT = [5, 10] #  количество полных свапов на https://www.abs.xyz/trade (свап туда-обратно)
ABSTRACT_SWAP_AMOUNT = ["1", "2"] # сумма свапов на https://www.abs.xyz/trade. Применяется только к ETH, обратно 100%

ABSTRACT_PENGU_TIP_AMOUNT = [1, 5] # количество PENGU для типов (донатов) стримерам. [min, max] - указывать в токенах

ABSTRACT_LINK_DISCORD = true # привязывать аккаунт Discord к профилю Abstract
ABSTRACT_LINK_TWITTER = true # привязывать аккаунт Twitter к профилю Abstract

ABSTRACT_VOTE_DAPPS = [''] # если указать названия приложения, то софт будет голосвать ислючительно по ним. Пример: ABSTRACT_VOTE_DAPPS = ['Pandora Swap', 'Gacha']

# abstract_buy_wanted_token, укажите токены, которые софт купит через Relay, если указать несколько, будет выбран один из
ABSTRACT_WANT_TO_BUY_TOKENS = [
    "0x123"
]

#-------------------------------------------------------Moonshot--------------------------------------------------------

ABSTRACT_MOONSHOT_AUTO_REFUEL = false # автоматический рефьюл если баланс меньше 0.0011 ETH (минималка под свап 0.001 на сайте)
ABSTRACT_MOONSHOT_COUNT = [6, 12] # количество полных свапов на https://dexscreener.com/abstract/ (свап туда-обратно)
ABSTRACT_MOONSHOT_SLEEP = [2, 3] # сон после покупки/продаже токенов на https://dexscreener.com/abstract/
ABSTRACT_MOONSHOT_CURVE_PROGRESS = 50 # максимальный прогрес токена до миграции с MoonShot
ABSTRACT_MOONSHOT_AMOUNT = ["5", "10"] # сумма ETH для покупки токенов, обратный свап на 100%

ABSTRACT_MOONSHOT_ADDRESSES = [ # контракты токенов с https://dexscreener.com/abstract/ для рандомного минта
#    "0xaa768eb64e5e158490a7c6610fcf684e08911995",
#    "0x903E1c5afc16638cDe01B66390e1f6CEFA0d6bdB",
#    "0x302ea2fCcad9E78672d6080212BA7f4DB4C708Fd",
]

#-------------------------------------------------------NFTs2Me---------------------------------------------------------

ABSTRACT_NFTS2ME_CONTRACTS = [ # контракты NFT с Nfts2me для рандомного минта
    "0x2597EB04120A9bE05d8552e1B1122189C83F350c",
    "0x924C1eCEd0F7667A56eafD3bFEce1B5d08BE2934",
    "0xE12D7f82Fa77b11cd72292c5Dfa681Acf5bcf50f",
    "0xdee880A0aF889945Dda8C9E451C2C9243a5bddf8",
    "0x9c093577A3B65EDd6E0BF54eFbbb4c2A55181e5E",
    "0xd0C0a3Cda42819134A7480D28C2181C8347B4E8E",
]

#------------------------------------------------------Zeroland---------------------------------------------------------

ABSTRACT_LANDING_AMOUNT = ["55", "60"]  # Применяется для депозитов на лендинг, вывод на 100%

#-------------------------------------------------------Dinero----------------------------------------------------------

ABSTRACT_DINERO_AMOUNT = ["55", "60"]  # Применяется для депозитов на https://abstract.dinero.xyz/app, вывод на 100%

#-------------------------------------------------------ZOOFUN----------------------------------------------------------

ABSTRACT_ZOOFUN_TOKENS = [ # контракты токенов с https://www.zoo.fun для рандомного свапа
    "0x06b230f356cec701f1b636fe2f6d173c89b29ffc",
    "0x183eca9e7cf4fcab0ad8a5bec0c9b7c9741c2edd",
    "0x2e17bcd6cc0f67401d736d1dd8284fda1e0d9168",
    "0x10e6e5f4efd605e2037d80976fc330bdc04f4c86",
    "0x133f086a628d366a1f91c347af366d142552d03b",

]

ABSTRACT_ZOOFUN_COUNT = [1, 3] # количество полных свапов на https://www.zoo.fun (1 свап - свап туда-обратно)
ABSTRACT_ZOOFUN_AMOUNT = ["1", "2"] # сумма свапов на https://www.zoo.fun. Применяется только к ETH, обратно 100%
ABSTRACT_ZOOFUN_SLEEP = [20, 30] # задержка между каждым свапом на https://www.zoo.fun

#-------------------------------------------------------Roach-----------------------------------------------------------

ABSTRACT_WANTED_TRAX_BALANCE = [10, 10] # желаемый баланс TRAX (мин, макс) (abstract_buy_trax_roach)

#------------------------------------------------------MagicEden--------------------------------------------------------

# abstract_deploy_me_token
ABSTRACT_TOKENS_METADATA = [
    ['Zalupa', 'ZLP', 'Too big to handle'],
    ['GigaZlp', 'GZLP', 'Only for true degens'],
    ['FullZlp', 'FZLP', 'Maxed out degen vibes'],
    ['RugPro', 'RUG', 'Exit fast, cry faster'],
    ['Insdr', 'INS', 'Alpha so good, you lose'],
    ['PumpX', 'PMP', 'Pump now, regret forever'],
    ['DgnDAO', 'DGN', 'Run by finest apes'],
    ['ScamX', 'SCM', 'Best scam on chain'],
    ['ZUtil', 'ZERO', 'Zero utility, max hype'],
    ['FomoInu', 'FMI', 'Buy high, never sell'],
    ['YoloX', 'YOX', 'All in, no way out'],
    ['MoonBoi', 'MNB', 'To the floor, fast'],
    ['ExitX', 'EXT', 'Exit before you blink'],
    ['SimpTok', 'SMP', 'For ultimate bagholders'],
    ['Hopium', 'HPM', 'Keep dreaming, forever broke'],
    ['Dusty', 'DST', 'Leftover bags forever'],
    ['RektX', 'REK', 'Instant rekt experience'],
    ['DumpIt', 'DMP', 'Sell now, thank me later'],
    ['Bagz', 'BGZ', 'Heaviest bags in town'],
    ['WenMoon', 'WEN', 'Soon™ and never'],
    ['CryNow', 'CRY', 'Perfect for salty tears'],
    ['FlipIt', 'FLP', 'Buy, flip, disappear'],
    ['TopBuy', 'TOP', 'Buy at absolute top'],
    ['HodlX', 'HDX', 'Hold forever, regret daily'],
    ['ApeIn', 'APE', 'No think, just buy']
]

# abstract_mint_me_terminal
ABSTRACT_MAGICEDEN_MINT_ALL = false  # поставьте true, чтобы софт заминтил кажду из NFT в списке ABSTRACT_MAGICEDEN_NFT_CONTRACTS, предварительно перемешав их
ABSTRACT_MAGICEDEN_MINT_LIMIT = true # минтить NFT только 1 раз или нет
ABSTRACT_MAGICEDEN_NFT_CONTRACTS = [ # адреса для рандомного минта NFT с https://magiceden.io/mint-terminal/abstract
#   "0x561646473cbd6f7134a33175f67c018b4ec2d661", # FREE
#   "0xebc038368dad99934ddf229c8da4dd48502c0605", # FREE
#   "0x7f95f671f4ca6b4a37673946acf28078906dcea0", # FREE
   "0x453c8e26e5c6277d8b8b7864a5d98d299d634289", # FREE
]

# abstract_buy_me_nft
ABSTRACT_MAGICEDEN_NFT_CONTRACTS_COLLECTION = [ # адреса для рандомного минта NFT с https://magiceden.io/collections/abstract
   "0xa22f3f9154b0f0e6b3266661e86645d00633ec2d", # 0.00006 ETH
]