CAMP_PROCESS_TWITTER = true # включает выполнение Twitter квестов
CAMP_PROCESS_DISCORD = false # включает выполнение Discord квестов
CAMP_PROCESS_ONCHAIN = true # включает выполнение On-Chain квестов
CAMP_PROCESS_CLICK = true # включает выполнение квестов, которые можно просто протыкать
CAMP_FETCH_PROGRESS = true # выключает проверку уже выполненных квестов, выключив уменьшит расход проксей х10