ECLIPSE_CEX_USING = 1                        # какую биржу использовать для работы: 1 - OKX, 4 - Bitget

# При работе с Bitget, лимит на вывод из Arbitrum 0.01, поэтому удалите Arbitrum из ECLIPSE_CEX_NETWORKS
ECLIPSE_CEX_NETWORKS = [2, 3, 6]             # какие сети использовать для вывода с биржи под рефьюел (2-Arbitrum, 3-Optimism, 6-Base)
ECLIPSE_CEX_AMOUNT = ['100', '100']          # сумма вывода SOL в сеть SOL. Можно указывать % или кол-во
ECLIPSE_USENEXUS_AMOUNT = ['100', '100']     # сумма SOL для бриджей между Solana и Eclipse. Можно указывать % или кол-во

ECLIPSE_CEX_ETH_L2_WITHDRAW = true           # включает предварительный вывод с биржи перед рефьюлом
ECLIPSE_GAZZIP_NETWORKS = ['Arbitrum', 'Optimism', 'Base'] # сети, в которых искать ETH для рефьюла через Gazzip
ECLIPSE_GAZZIP_AMOUNT = [0.0013, 0.0014]     # сумма вывода ETH с биржи в ECLIPSE_CEX_NETWORKS, для рефьюла через Gazzip.
ECLIPSE_WETH_BRIDGE_AMOUNT = [0.001, 0.002]  # сумма WETH для бриджа через https://app.eclipse.xyz/mint-teth

ECLIPSE_SOLAR_SWAP_AMOUNT = ['10', '15']  # сумма для свапов на платформе https://eclipse.solarstudios.co/
ECLIPSE_ORCA_SWAP_AMOUNT = ['10', '15']  # сумма для свапов на платформе https://www.orca.so/