ECLIPSE_TAP_AUTO_REFUEL = true # делать автоматический рефьюл для пополнения сети Eclipse

ECLIPSE_CEX_USING = 1                        # какую биржу использовать для работы: 1 - OKX, 4 - Bitget

# При работе с Bitget, лимит на вывод из Arbitrum 0.01, поэтому удалите Arbitrum из ECLIPSE_CEX_NETWORKS
ECLIPSE_CEX_NETWORKS = [2, 3]             # какие сети использовать для вывода с биржи под рефьюел (2-Arbitrum, 3-Optimism, 6-Base)
ECLIPSE_CEX_ETH_L2_WITHDRAW = true           # включает предварительный вывод с биржи перед рефьюлом
ECLIPSE_GAZZIP_NETWORKS = ['Arbitrum', 'Optimism'] # сети, в которых искать ETH для рефьюла через Gazzip
ECLIPSE_GAZZIP_AMOUNT = [0.0008, 0.0009]     # сумма вывода ETH с биржи в ECLIPSE_CEX_NETWORKS, для рефьюла через Gazzip.

ECLIPSE_TAP_SLEEP_TIME = [0.1, 0.2]            # [от, до] время сна между каждым кликом
ECLIPSE_TAP_SLEEP_TIME2 = [60, 120]         # [от, до] время сна между каждыми 500 кликами
ECLIPSE_TAP_SLEEP_TIME3 = [250, 400]         # [от, до] время сна между каждой 1000 кликов
ECLIPSE_TAPS_AMOUNT = [9000, 9800]          # [от, до] максимальное количество кликов на аккаунте
