ECLIPSE_CEX_USING = 1                        # какую биржу использовать для работы: 1 - OKX, 4 - Bitget
ECLIPSE_CEX_NETWORKS = [2, 3]                # какие сети использовать для вывода с биржи под рефьюел (2 - Arbitrum, 3 - Optimism)
ECLIPSE_CEX_AMOUNT = ['100', '100']          # сумма вывода SOL в сеть SOL. Можно указывать % или кол-во

ECLIPSE_USENEXUS_AMOUNT = ['100', '100']     # сумма SOL для бриджей между Solana и Eclipse. Можно указывать % или кол-во
ECLIPSE_GAZZIP_AMOUNT = [0.0013, 0.0014]     # сумма вывода ETH с биржи в рандомную L2 сеть, для рефьюла через Gazzip.

ECLIPSE_WETH_BRIDGE_AMOUNT = [0.001, 0.002]  # сумма WETH для бриджа через https://app.eclipse.xyz/mint-teth