#-----------------------------------------------------TAPS CONTROL------------------------------------------------------

ECLIPSE_TAP_NEW_DEPOSITS = true              # делать депозиты на новые/старые игровые кошельки после первого депозита
ECLIPSE_TAP_GEN_NEW_WALLETS = false          # создавать каждый раз новый кошелек при депозите для тапов
ECLIPSE_TAP_ONCHAIN_POINTS_CHECK = false     # проверять количество поинтов через Onchain (позволяет считать поинты только за тапы)

ECLIPSE_TAP_AUTO_REFUEL = true               # делать автоматический рефьюл для пополнения сети Eclipse
ECLIPSE_GASZIP_NETWORKS = ['Arbitrum', 'Optimism']       # сети, в которых искать ETH для рефьюла через GasZip (Arbitrum, Optimism, Base)
ECLIPSE_GASZIP_AMOUNT = [0.00075, 0.00085]   # сумма вывода ETH с биржи в ECLIPSE_CEX_NETWORKS, для рефьюла через GasZip
ECLIPSE_GASZIP_FEE_SUPPORT = [0.000025, 0.000025] # сумма нативки удержания нативки под комиссию для реьюла через GasZip

#--------------------------------------------------TAPS SLEEP CONTROL---------------------------------------------------

ECLIPSE_TAP_SLEEP_TIME = [2, 4]         # [от, до] время сна между каждым кликом

ECLIPSE_TAP_SLEEP_AMOUNT2 = [400, 500]      # [от, до] количество тапов для сна ECLIPSE_TAP_SLEEP_TIME2
ECLIPSE_TAP_SLEEP_TIME2 = [60, 120]         # [от, до] время сна между каждыми ECLIPSE_TAP_SLEEP_AMOUNT2 кликами

ECLIPSE_TAP_SLEEP_AMOUNT3 = [1000, 1200]    # [от, до] количество тапов для сна ECLIPSE_TAP_SLEEP_TIME3
ECLIPSE_TAP_SLEEP_TIME3 = [250, 400]        # [от, до] время сна между каждой ECLIPSE_TAP_SLEEP_AMOUNT3 кликов

ECLIPSE_TAPS_AMOUNT = [9500, 9800]         # [от, до] максимальное количество кликов на аккаунте
ECLIPSE_TAPS_SESSION_AMOUNT = [2000, 4000]  # [от, до] максимальное количество кликов на аккаунте за сессию запуска софта
ECLIPSE_TAPS_AMOUNT_BATCH = [4, 7]           # [от, до] количество тапов за подход.