GALXE_CUSTOM_CAMPAIGNS_EVM = [
    'GCTgitgsQP',
]

GALXE_CUSTOM_CAMPAIGNS_APTOS = [
    'GCTgitgsQP',
]

GALXE_QUIZ_ANSWERS_BY_CREDENTIAL_ID = [
    [433653260763623424, [3, 2, 2, 0]],  # [QUIZ CREDITANTIONAL ID, [QUIZ ANSWERS]]
    [433653260763623425, [1, 3, 2, 0]],  # [QUIZ CREDITANTIONAL ID, [QUIZ ANSWERS]]
    [433653260763623426, [1, 2, 3, 0]],  # [QUIZ CREDITANTIONAL ID, [QUIZ ANSWERS]]
    [433653260763623427, [1, 2, 2, 3]],  # [QUIZ CREDITANTIONAL ID, [QUIZ ANSWERS]]
]