GALXE_CUSTOM_CAMPAIGNS_EVM = [
    'GC4LctVfyZ',
]

GALXE_CUSTOM_CAMPAIGNS_APTOS = [
    'GCjjvtVTbn',
]

# A-1, B-2, C-3, D-4, E-5, F-6 и так далее. Ответы словами не поддерживаются.
GALXE_QUIZ_ANSWERS_BY_CREDENTIAL_ID = [
    [433653260763623424, 3, 2, 2, 0],  # [QUIZ CREDITANTIONAL ID, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER]
    [433653260763623425, 1, 3, 2, 0],  # [QUIZ CREDITANTIONAL ID, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER]
    [433653260763623426, 1, 2, 3, 0],  # [QUIZ CREDITANTIONAL ID, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER]
    [433653260763623427, 1, 2, 2, 3],  # [QUIZ CREDITANTIONAL ID, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER, QUIZ ANSWER]
]
