#--------------------------------------------------INKONCHAIN CONTROL---------------------------------------------------

INK_RESERVOIR_SWAP_AMOUNT = ['80', '90']    # % ETH, которое будет использовано для свапов на swap.reservoir.tools
INK_VELODROME_SWAP_AMOUNT = ['80', '90']    # % ETH, которое будет использовано для свапов на velodrome.finance
INK_ETH_WRAP_AMOUNT = ['80', '90']          # % ETH, которое будет использовано для врапа в WETH
