IRYS_CAMPAIGNS_TO_SKIP = [            # Какие кампании пропустить и не пытаться клеймить
    "GC9PLtfbkT",
]

#"Irys Resources"                     : "GCVVCtmFyM",
#"Claim Testnet Tokens"               : "GCxxCtmLMP",
#"Follow Irys"                        : "GC17CtmBrm",
#"Play a Game on The Irys Arcade"     : "GC1mCtmb1N",
#"Irys Arcade Achievement Quests"     : "GCAHHtfmaV",
#"Play SpriteType 5 times (daily)"    : "GCLjLtf7zj",
#"Play Irys Arcade 5 times (daily)"   : "GCLVHtf1NL",
#"SpriteType Achievement Quests"      : "GCFtLtfrJH",

[[IRYS_ARCADE_GAMES]]                # Конфигурация игр Irys Arcade
name = "snake"                       # Название игры
games_min = 2                        # Минимальное количество игр за сессию
games_max = 4                        # Максимальное количество игр за сессию
score_min = 260                      # Минимальный целевой счёт
score_max = 550                      # Максимальный целевой счёт
duration_min = 300                   # Минимальная длительность игры (секунды)
duration_max = 600                   # Максимальная длительность игры (секунды)

[[IRYS_ARCADE_GAMES]]
name = "missile-command"
games_min = 2
games_max = 4
score_min = 110000
score_max = 450000
duration_min = 300
duration_max = 600

[[IRYS_ARCADE_GAMES]]
name = "hex-shooter"
games_min = 2
games_max = 4
score_min = 34000
score_max = 50000
duration_min = 300
duration_max = 600

[[IRYS_ARCADE_GAMES]]
name = "asteroids"
games_min = 2
games_max = 4
score_min = 51000
score_max = 210000
duration_min = 300
duration_max = 600

IRYS_ARCADE_SLEEP_BETWEEN = [20, 40] # Диапазон пауз между играми (секунды)
