#--------------------------------------------------- BETS FILTER -----------------------------------------------------
LIMITLESS_MARKET_MIN_VOLUME = 3000        # Минимальный объем ставки за всю историю
LIMITLESS_MIN_OUTCOME_PRICE = 80           # Минимальная цена дорогого исхода на ставке в ¢
LIMITLESS_MAX_OUTCOME_PRICE = 95           # Максимальная цена дорогого исхода на ставке в ¢
LIMITLESS_MAX_SPREAD_CENTS  = 3            # Максимальный спред на ставке в ¢

#--------------------------------------------------- BETS SETTINGS ---------------------------------------------------
LIMITLESS_BET_AMOUNT                  = ["90", "100"]  # Сумма ставки USDC
LIMITLESS_ALLOW_CLOSE_NON_HEDGED_BETS = true           # Закрывать ли нехеджированные позиции (пресет Close Bets и экстренное закрытие первой ставки при ошибке второй)

#--------------------------------------------------- CEX SETTINGS ----------------------------------------------------
# Аналогично с настройками CEX в settings.toml
LIMITLESS_WITHDRAW_CEX_ETH_AMOUNT     = [0.01, 0.015]

LIMITLESS_CEX_DEPOSIT_AMOUNT_ETH      = ["100", "100"]
LIMITLESS_CEX_DEPOSIT_LIMITER_ETH     = [0.0, 0.0]

#--------------------------------------------------- SWAP SETTINGS ---------------------------------------------------
LIMITLESS_ETH_SWAP_AMOUNT             = ["90", "95"]

#--------------------------------------------------- RUNTIME SETTINGS ------------------------------------------------
LIMITLESS_SLEEP_TIME_ACCOUNTS         = [20, 30]       # Сколько спать между действиями аккаунтов (сек)


# Cписок возможных ставок для функции Place Single Bet
# Формат: ["СТОРОНА", "slug"]
# - СТОРОНА: "YES" или "NO" — на какую сторону ставим
# - slug: уникальный идентификатор рынка (часть URL после "market=")
#
# Пример:
#   Ссылка на рынок: https://limitless.exchange/advanced?rv=7JOJOHZ3W7&market=us-recession-in-2025-1741284556247
#   Slug: us-recession-in-2025-1741284556247
#
# Логика работы:
# - Софт возьмет 1 случайную ставку из списка и сделает её
# - Можно указать несколько ставок, тогда выбор будет случайным
#
# Примеры добавления ставок:
#   ["YES", "bitcoin-100k-by-march"],
#   ["NO", "trump-tweet-today"],
#   ["YES", "eth-above-5000"],


LIMITLESS_BETS_LIST = [
    ["NO", "us-national-solana-reserve-in-2025-1748943996289"],
]