#--------------------------------------------------- BETS FILTER -----------------------------------------------------
LIMITLESS_MARKET_MIN_VOLUME = 10000        # Минимальный объем ставки за всю историю
LIMITLESS_MIN_OUTCOME_PRICE = 80           # Минимальная цена дорогого исхода на ставке в ¢
LIMITLESS_MAX_OUTCOME_PRICE = 95           # Максимальная цена дорогого исхода на ставке в ¢
LIMITLESS_MAX_SPREAD_CENTS  = 2            # Максимальный спред на ставке в ¢

#--------------------------------------------------- BETS SETTINGS ---------------------------------------------------
LIMITLESS_BET_AMOUNT                  = ["90", "100"]  # Сумма ставки USDC
LIMITLESS_ALLOW_CLOSE_NON_HEDGED_BETS = true           # Закрывать ли нехеджированные позиции (пресет Close Bets и экстренное закрытие первой ставки при ошибке второй)

#--------------------------------------------------- CEX SETTINGS ----------------------------------------------------
LIMITLESS_WITHDRAW_CEX_ETH_AMOUNT     = [0.015, 0.03]

#--------------------------------------------------- SWAP SETTINGS ---------------------------------------------------
LIMITLESS_ETH_SWAP_AMOUNT             = ["90", "95"]

#--------------------------------------------------- RUNTIME SETTINGS ------------------------------------------------
LIMITLESS_SLEEP_TIME_ACCOUNTS         = [20, 30]       # Сколько спать между действиями аккаунтов (сек)
