#-----------------------------------------------MONAD AUTO-PRESET CONTROL-----------------------------------------------

# monad_refuel_from_sepolia_eth
MONAD_MIN_MON_BALANCE = 1.0 # необходимый баланс MON, чтобы софт пропускал аккаунт при запуске функции monad_refuel_from_sepolia_eth
MONAD_MIN_TO_BRIDGE = 1.0 # минимальное количество MON для бриджа через MWDAO, при запуске monad_bridge_mwdao

# monad_process_onchain_activity
MONAD_WANTED_TX_COUNT = [45, 65]  # необходимое количество транзакций на аккаунте
MONAD_WANTED_TX_COUNT_SESSION = [10, 15]  # необходимое количество транзакций за 1 запуск софта при отработке MONAD_WANTED_TX_COUNT

# какие модули нужны в автоматическом подборе при запуске функции monad_process_onchain_activity
MONAD_AUTO_MODULES = ["Swaps", "Stakes", "Mints", "Domains"] # доступны следующие модули: Swaps, Stakes, Mints, Domains

# monad_smart_swaps
# monad_smart_swap_eth_mon
MONAD_SWAP_DAPPS = ["zkSwap"] # дапки для свапов, если убрать все дапки, то свапать не будет. Доступны: Bean, Izumi, Ambient, zkSwap
MONAD_SWAPS_AMOUNT = ["55", "60"] # количество MON для свапов, обратно в MON применяется 100%

#---------------------------------------------------TALENTUM CONTROL----------------------------------------------------

MONAD_TALENTUM_CHECKER = true # проверять статистику при запуске чекера
MONAD_TALENTUM_TOTAL_QUESTS = [50, 70] # количество квестов к выполнению на аккаунт за 1 запуск модуля

MONAD_TALENTUM_PROCESS_FAUCET = true # клеймить ли токены при логине на кране Talentum
MONAD_TALENTUM_PROCESS_STAKE = true # делать ли задания со стейком. Стоимость 0.1 MON
MONAD_TALENTUM_PROCESS_MINT = true # делать ли задания с минтами NFT. Стоимость 0.1 MON
MONAD_TALENTUM_PROCESS_TWITTER = false # делать ли задания с твиттерами.
MONAD_TALENTUM_PROCESS_SPECIAL = false # делать ли специальные задания (реализованные отдельным модулем, часто затраты на них больше)

MONAD_TALENTUM_LINK_TWITTER = false # привязывать твиттер к профилю, если задание этого требует
MONAD_TALENTUM_ID_PROCESS_SOCIAL = false # пытаться ли заклеймить поинты за социалки для минта Talentum ID (true если не хватает поинтов за ончейн)
MONAD_TALENTUM_SPECIFIC_QUESTS = [ # id квестов для выполнения, будут перемешаны (monad_process_talentum_specific_quests)
   4680,
]

#----------------------------------------------------MONAD CONTROL------------------------------------------------------

MONAD_FAUCET_CLAIMED_COUNT = 2      # количество попыток заклеймить кран при сообщении "Faucet was already claimed"
MONAD_FAUCET_WAIT_TIME = [240, 360] # время сна при ошибках на кране, чтобы проверить баланс, на случай если кран смог выдать токены

MONAD_STAKE_AMOUNT = [0.001, 0.005] # сумма для стейка MON (минимум, максимум) (% или кол-во)
MONAD_TRANSFERS_AMOUNT = ["100", "100"] # количество MON для трансфера на EVM Deposit Address

#-------------------------------------------------GASZIP FAUCET CONTROL-------------------------------------------------

MONAD_GASZIP_TX_WANTED = [10, 15] # количество желаемых транзакций для крана на https://www.gas.zip/faucet/monad
MONAD_GASZIP_AMOUNT = [0.00066, 0.00087] # сумма рефьюла через Gas.Zip

#---------------------------------------------------BRIDGE MON CONTROL--------------------------------------------------

# monad_bridge_mwdao_in
# monad_smart_monadbridge
# monad_process_onchain_activity
MONAD_WANT_BALANCE = [15, 20] # сумма MON на балансе в Monad, при не хватке, софт запустит процесс вывода + рефьюла в сеть

# monad_bridge_mwdao_in
MONAD_MWDAO_BRIDGE_AMOUNT = ['100', '100'] # сумма ETH для бриджа через https://bridge.mwdao.xyz/
MONAD_MWDAO_BRIDGE_NETWORKS = ["Arbitrum", "Optimism", "Base"] # сети, которые используются для бриджа через https://bridge.mwdao.xyz/

# monad_testnet_bridge_to_sepolia
MONAD_TESTNET_BRIDGE_MIN_AMOUNT = 1 # необходимый баланс ETH в сети Sepolia, чтобы софт НЕ запускал бридж из L2 в Sepolia
MONAD_TESTNET_BRIDGE_AMOUNT = [0.0001, 0.0002] # сумма бриджа из L2(Arbitrum или Optimism) в Sepolia (минимум, максимум) (% или кол-во)

# monad_orbiter_bridge_to_monad
MONAD_BRIDGE_AMOUNT = ["100", "100"] # сумма бриджа ETH Sepolia -> ETH Monad через Orbiter

# monad_smart_monadbridge
MONAD_MONADBRIDGE_AMOUNT = ['100', '100'] # сумма бриджа ETH Sepolia -> wWETH Monad через MonadBridge

#--------------------------------------------------DISPERSE MON CONTROL-------------------------------------------------

MONAD_AMBIENT_DISPERSE_MAPPING = [ # настройки для раскидки токенов на адреса Bitcoin Deposit Address. Формат: ["x", "y", "z"],
   ["Main 1", "1", "10"],          # где x - имя аккаунта, с которого будут отправлены токены, y - стартовый номер адреса из Bitcoin Deposit Address,
   ["Main 2", "11", "30"]          # z - конечный номер адреса из Bitcoin Deposit Address (включительно). Будет взят весь диапазон.
]
MONAD_AMBIENT_DEPOSIT_AMOUNT = [100, 120] # сумма депозита на https://monad.ambient.finance/ (минимум, максимум) (% или кол-во)
MONAD_AMBIENT_TRANSFER_AMOUNT = [3, 5] # сумма трансфера на https://monad.ambient.finance/ (минимум, максимум) (% или кол-во)

#---------------------------------------------------MODULES CONTROL-----------------------------------------------------

# monad_buy_blink_tokens
MONAD_BLINK_TOKENS = ['DAK', 'YAKI', 'CHOG'] # токены для свапов на https://testnet.monad.xyz/. Доступны: CHOG, YAKI, DAK
MONAD_BLINK_AMOUNT = ['0.1', '0.2'] # сумма свапов на https://testnet.monad.xyz/

# monad_swap_nadfun
MONAD_NUDFUN_SWAP_AMOUNT = [0.05, 0.1] # сумма свапов на https://testnet.nad.fun/, применяется для MON, обратно 100%

# monad_create_token_nadfun
MONAD_NUDFUN_INITIAL_BUY_AMOUNT = [0.1, 0.2] # сумма для обязательной изначальной покупки созданного токена на https://testnet.nad.fun/

# monad_deploy_me_token
# monad_create_token_nadfun
MONAD_TOKENS_METADATA = [
    ['Zalupa', 'ZLP', 'Too big to handle'],
    ['GigaZlp', 'GZLP', 'Only for true degens'],
    ['FullZlp', 'FZLP', 'Maxed out degen vibes'],
    ['RugPro', 'RUG', 'Exit fast, cry faster'],
    ['Insdr', 'INS', 'Alpha so good, you lose'],
    ['PumpX', 'PMP', 'Pump now, regret forever'],
    ['DgnDAO', 'DGN', 'Run by finest apes'],
    ['ScamX', 'SCM', 'Best scam on chain'],
    ['ZUtil', 'ZERO', 'Zero utility, max hype'],
    ['FomoInu', 'FMI', 'Buy high, never sell'],
    ['YoloX', 'YOX', 'All in, no way out'],
    ['MoonBoi', 'MNB', 'To the floor, fast'],
    ['ExitX', 'EXT', 'Exit before you blink'],
    ['SimpTok', 'SMP', 'For ultimate bagholders'],
    ['Hopium', 'HPM', 'Keep dreaming, forever broke'],
    ['Dusty', 'DST', 'Leftover bags forever'],
    ['RektX', 'REK', 'Instant rekt experience'],
    ['DumpIt', 'DMP', 'Sell now, thank me later'],
    ['Bagz', 'BGZ', 'Heaviest bags in town'],
    ['WenMoon', 'WEN', 'Soon™ and never'],
    ['CryNow', 'CRY', 'Perfect for salty tears'],
    ['FlipIt', 'FLP', 'Buy, flip, disappear'],
    ['TopBuy', 'TOP', 'Buy at absolute top'],
    ['HodlX', 'HDX', 'Hold forever, regret daily'],
    ['ApeIn', 'APE', 'No think, just buy']
]

# monad_mint_me_terminal
MONAD_MAGICEDEN_MINT_ALL = false  # поставьте true, чтобы софт заминтил кажду из NFT в списке MONAD_MAGICEDEN_NFT_CONTRACTS, предварительно перемешав их
MONAD_MAGICEDEN_MINT_LIMIT = true # минтить NFT только 1 раз или нет
MONAD_MAGICEDEN_NFT_CONTRACTS = [ # адреса для рандомного минта NFT с https://magiceden.io/mint-terminal/monad-testnet
   "0xc8cfc763702c87ff14183c76a44cce602447c9e3", # FREE
   "0xd3026d7111b34faf30a2c7389a3c111e2656bfed", # FREE
   "0xde81390a761deb3708b8ce5e7ec99a880a392eb6", # FREE
   "0x47ce0e7e05e3fea9767265e077bc7c0531de3bbf", # FREE
   "0xcbfda8ade65c843289c1fd89778fe3d6f95a1777", # FREE
   "0x4e21dbdcb17e7ead0e2dc4e83e6b48cdb8e8c449", # FREE
   "0x2a22e1dcc3f6b46465260388f4fdb677d1eb5f7d", # FREE
   "0x21fd600fb5322f1a15d9f9607ee28a60355b6fae", # FREE
]

# monad_smart_bets_levr
MONAD_LEVR_BETS_COUNT = [5, 7]  # необходимое количество ставок на https://app.levr.bet/march-madness
MONAD_LEVR_MAXIMUM_BETS_AMOUNT = [50, 100] # сумма ставки, которую софт не будет превышать, но берется рандомно не из этого диапазона

# monad_claim_atlantis_nft
MONAD_ATLANTIS_MAX_NFT_COUNT = [1, 1] # количество NFT которое аккаунт должен заминтить, каждый минт требует делать по 20 свапов

# monad_mint_mubond
MONAD_MINT_MUBOND_AMOUNT = [0.5, 1.2] # количество MON, которое изпользуется на минт $muBOND

# monad_play_2048

# Включить оптимизированную стратегию (поиск лучшего хода).
# false — случайные ходы. true — лучше играет, но может нагружать систему и ход подбирается достаточно долго.
MONAD_2048_OPTIMIZED_STRATEGY = true

# Диапазон задержки между ходами (в секундах) для имитации поведения игрока.
# Пример: [0.0, 0.0] — без задержек. [0.5, 1.5] — паузы от 0.5 до 1.5 сек.
MONAD_2048_STEP_SLEEP = [0.0, 0.0]

# Диапазон суммы депозита (в MON), отправляемой на embedded-кошелёк перед стартом игры.
# Значение выбирается случайно из указанного диапазона.
MONAD_2048_EMBEDDED_WALLET_DEPOSIT = [0.85, 1.1]
MONAD_2048_EMBEDDED_WALLET_NEW_DEPOSITS = false # делать новые депозиты на игровой кошелек, если баланс опуститься ниже 0.01 MON

#--------------------------------------------------AVAILABLE MODULES----------------------------------------------------

#  monad_claim_faucet                     # Клейм MON на оф. кране https://testnet.monad.xyz/
#  monad_bridge_mwdao_in                  # бридж через https://bridge.mwdao.xyz/, работает по MONAD_MWDAO_BRIDGE_AMOUNT и MONAD_MWDAO_BRIDGE_NETWORKS
#  monad_smart_monadbridge                # бридж ETH -> wWETH через https://monadbridge.com/ + свап на Ambient, работает по MONAD_MONADBRIDGE_AMOUNT
#  monad_smart_bridge_mwdao_in            # умный бридж через https://bridge.mwdao.xyz/, работает по MONAD_WANT_BALANCE и MONAD_MIN_TO_BRIDGE
#  monad_smart_refuel_monad               # умный рефьюл через Gas.Zip, работает по REFUEL CONTROL

#  monad_process_talentum_quests          # Запуск отработки Talentum квестов
#  monad_mint_id_talentum                 # Запуск клейма Talentum ID NFT на https://monad.talentum.id/verification
#  monad_process_talentum_specific_quests # Запуск отработки выбранных Talentum квестов (MONAD_TALENTUM_SPECIFIC_QUESTS)
#  monad_process_daily_activity           # Выполнение дейликов на Talentum (клейм крана + MON streak)

#  monad_process_onchain_activity         # Выполнение модулей в автоматическом режиме по настройкам MONAD AUTO-PRESET CONTROL
#  monad_refuel_from_sepolia_eth          # Пополение баланса MON через маршрут: TestnetBridge --> Obriter --> Swap ETH -> MON

#  monad_testnet_bridge_to_sepolia        # Бридж ETH L2 -> ETH Sepolia через TestnetBridge, сумма под бридж MONAD_TESTNET_BRIDGE_AMOUNT
#  monad_orbiter_bridge_to_monad          # Бридж ETH Sepolia -> ETH Monad через Orbiter, сумма под бридж MONAD_BRIDGE_AMOUNT
#  monad_smart_swap_eth_mon               # Свапы ETH Monad -> MON Monad через дапки в настройке MONAD_SWAP_DAPPS

#  monad_deploy_me_token                  # Deploy NFT на MagicEden через Mint Terminal по настройке MONAD_TOKENS_METADATA
#  monad_mint_me_terminal                 # Mint NFT на MagicEden через Mint Terminal по настройке MONAD_MAGICEDEN_NFT_CONTRACTS
#  monad_mint_nad_domain                  # регистрация .nad домена на https://app.nad.domains/. Стоимость 0.1 MON
#  monad_make_predict_castora             # Делает рандомный предикт цены в одном из пулов на https://castora.xyz/. Стоимость 0.2 MON
#  monad_smart_bets_levr                  # Делает ставки на https://app.levr.bet по настройкам MONAD_LEVR_BETS_COUNT и MONAD_LEVR_MAXIMUM_BETS_AMOUNT
#  monad_play_fantasy                     # Делает регистрацию по Твиттеру и записывает данные в файл (data/services/privy_wallets.json), клеймит начальную колоду, клеймит токены, регистрируется на бронз и сильвер турниры

#  monad_stake_mon_apriori                # Стейк MON на https://stake.apr.io/. сумма стейка по MONAD_STAKE_AMOUNT
#  monad_stake_mon_magma                  # Стейк MON на http://magmastaking.xyz/. сумма стейка по MONAD_STAKE_AMOUNT
#  monad_stake_mon_kintsu                 # Стейк MON на https://stake.apr.io/. сумма стейка по MONAD_STAKE_AMOUNT (минималка 0.01 MON)
#  monad_stake_and_commit_shmonad         # Стейк MON на https://www.shmonad.xyz/. сумма стейка по MONAD_STAKE_AMOUNT
#  monad_uncommit_and_redeem_shmonad      # Анстейк MON на https://www.shmonad.xyz/. выводит 100%

#  monad_request_unstake_mon_kintsu       # Запрос на вывод из KintSu, софт сделает запрос на вывод, который разблокируется через 14 дней
#  monad_request_unstake_mon_apriori      # Запрос на вывод из Apriori, софт сделает запрос на вывод и будет ждат 10 мин для его завершения
#  monad_request_unstake_mon_magma        # Запрос на вывод из Magma, софт сделает мгновенный вывод

#  monad_claim_gaszip_faucet              # Клейм $MON на кране Gas.Zip
#  monad_smart_gaszip_refuels             # Рефьюлы на Gas.Zip для набития кол-ва транз по настройке MONAD_GASZIP_TX_WANTED, суммы и сети по старым настройкам из REFUEL CONTROL

#  monad_wrap_native                      # Wrap + Unwrap MON, настройка автоматическая
#  monad_smart_swaps                      # Умные двойные свапы, работают на Ambient, Izumi, zkSwap, Bear, сумма свапов по MONAD_SWAPS_AMOUNT, дапки по MONAD_SWAP_DAPPS, ограничение в 5 MON, во избежания слипаджа
#  monad_swap_nadfun                      # Свапы на Nad.Fun. Покупка и продажа рандомных щитков на сумму MONAD_NUDFUN_SWAP_AMOUNT
#  monad_buy_blink_tokens                 # Свапы на https://testnet.monad.xyz/, работает по MONAD_BLINK_TOKENS и MONAD_BLINK_AMOUNT
#  monad_smart_buy_blink_tokens           # Свапы с проверкой баланса (покупает 3 токена в рандомном продке, если нету баланса токена) на https://testnet.monad.xyz/, работает по MONAD_BLINK_AMOUNT

#  monad_deposit_mon_ambient               # депозит MON на https://monad.ambient.finance/ (см DISPERSE MON CONTROL)
#  monad_withdraw_mon_ambient              # вывод MON с https://monad.ambient.finance/
#  monad_disperse_mon_ambient              # раскидка MON используя https://monad.ambient.finance/

#  monad_claim_atlantis_nft                # минт NFT за 20 свапов, на https://app.atlantisdex.xyz/mint-nft, работает по MONAD_ATLANTIS_MAX_NFT_COUNT

#  monad_create_token_nadfun               # создание токена на https://testnet.nad.fun/ (см. MONAD_NUDFUN_INITIAL_BUY_AMOUNT и MONAD_TOKENS_METADATA)
#  monad_complete_all_missions_nadfun      # протыкивает все миссии на https://testnet.nad.fun/

#  monad_mint_mubond                       # минтит $muBOND на https://testnet.mudigital.net/ (смю MONAD_MINT_MUBOND_AMOUNT)

#  monad_collect_mon                       # Сбор всех токенов в MON, свапает на рандомном дексе
#  monad_transfer_mon                      # Трансфер MON на адрес EVM Deposit Address
