#----------------------------------------------------MONAD+ CONTROL-----------------------------------------------------

# monad_kizzy_place_bets
# Для выполнения дейликов нужно ставить от 15 KESO

MONAD_KIZZY_BETS_PER_RUN = [2, 4]            # Диапазон количества ставок за один запуск
MONAD_KIZZY_BET_AMOUNTS = [15.1, 20.0]       # Диапазон суммы каждой ставки (в KESO)
