#-------------------------------------------------------POSEIDON--------------------------------------------------------

# Список языков для выполнения заданий (поддерживается любой язык из приложения)
POSEIDON_WANTED_LANGUAGES = ['Russian', 'German', 'French']

# Количество уникальных языков для 1 аккаунта
POSEIDON_WANTED_LANGUAGES_COUNT = [1, 3]

# Количество квестов для выполнения за один запуск модуля
POSEIDON_QUEST_PRE_RUN = [4, 5]

# Если установлено true, браузер будет запускаться в фоновом режиме (без графического интерфейса)
POSEIDON_HEADLESS_MODE = false

#-----------------------------------------------------ELEVEN LABS-------------------------------------------------------

# API-ключ для сервиса Eleven Labs: https://elevenlabs.io/app/developers/api-keys
POSEIDON_ELEVEN_API_KEY = ""

# Режим работы API Eleven Labs:
# 1 - использовать Eleven V3
# 2 - использовать Eleven V2.5 Turbo
POSEIDON_ELEVEN_API_MODE = 1 # 1 - Eleven V3, 2 - Eleven V2.5 Turbo

# Тип голоса для озвучки текста в Eleven Labs:
# 1 - personal: голос, созданный вами на сайте (100%). Ссылка для создания: https://elevenlabs.io/app/voice-lab?action=create
# 2 - default: готовый голос из публичной библиотеки Eleven (30-50%)
POSEIDON_ELEVEN_VOICE_TYPE = 1 # 1 - personal, 2 - default
