#----------------------------------------------------PUMPFUN CONTROL----------------------------------------------------

PUMPFUN_CEX_USING = 1                         # какую биржу использовать для работы: 1 - OKX, 4 - Bitget
PUMPFUN_CEX_AMOUNT = ['100', '100']           # сумма вывода SOL в сеть SOL. Можно указывать % или кол-во
PUMPFUN_CEX_SOL_LIMITER = [0.3, 0.4]          # количество SOL в $, которое нужно оставить на аккаунте при депозите на Биржу

PUMPFUN_SLEEP_TIME_SELL = [0, 0]              # время сна между покупкой и продажей токенов (мин, макс)
PUMPFUN_SWAP_AMOUNT = ['10', '20']            # сумма SOL для свапов SOL -> SHITCOIN (обратно 100%)

PUMPFUN_SHITCOIN_CONTRACTS = [                # контракты шиткойнов для покупки на pump.fun
    'C1nYn2Bfq4fw3hcYB69xjquUguLqtRPcn5nTqtZcpump',
    'C1nYn2Bfq4fw3hcYB69xjquUguLqtRPcn5nTqtZcpump',
    'C1nYn2Bfq4fw3hcYB69xjquUguLqtRPcn5nTqtZcpump',
]

#------------------------------------------------TRANSACTION PROTECTION-------------------------------------------------

# Адрес валидатора, который будет проталкивать вашу транзакцию. По умолчанию стоит сервис https://bloxroute.com/
PUMPFUN_PRIORITY_FEE_RECIPENT = "HWEoBxYs7ssKuudEjzjmpfJVX7Dvi7wescFsVx2L5yoY"
PUMPFUN_PRIORITY_FEE = [0, 0]            # приоритетная комсиссия для оправки транзакции (мин, макс). Минимум 0.002 SOL.
PUPMFUN_USE_PUMPFUN_RPC = true           # использование RPC pump.fun, требуется решение капчи для каждой транзакции
PUPMFUN_USE_FRONTRUN_PROTECTION = false  # включение защиты от MEV ботов, если включаете, то PUMPFUN_PRIORITY_FEE должно быть хотя бы 0.01 SOL
PUPMFUN_SLIPPAGE = 25                    # указывайте слипадж в %, чем меньше - тем больше шанс, что транзакция зафейлится

#---------------------------------------------------PUMPFUN ADVANCED----------------------------------------------------

PUMPFUN_ADVANCED_LOGIN_VIA_MAIL = false           # входить в аккаун через почту, используя кошелек Privy

# работает только для Auto-trading
PUMPFUN_MARKET_CAP_FILTER = [20000, 80000]            # фильтр поиска токенов по Market Cap
PUMPFUN_VOLUME_FILTER = [10000, 1000000]                # фильтр поиска токенов по Volume
PUMPFUN_NUM_HOLDERS_FILER = [20, 1000]            # фильтр поиска токенов по Holders Count
PUMPFUN_MAX_SNIPERS_COUNT = 1000                # максимальное количество снайперов в токене

#----------------------------------------------------TOKEN CREATION-----------------------------------------------------

PUMPFUN_TOKER_NAME = [
    ['ZalupaCoin', 'ZLP', 'This token is too good for buy, cuz zalupa is too big'],
#    ['GigaZalupa', 'GZLP', 'This token is too good for buy'],
#    ['FullZalupa', 'FZLP', 'This token is too good for buy']
] # Название токена, Название тикера, Описание токена

#-------------------------------------------------------REPLIES---------------------------------------------------------

PUMPFUN_REPLIES_LIST = [
    'PUMP IT',
    'PUMPPPPPP IT',
    'GOOOOOOD TOKEN',
] # любой текст прописывайте через запятую и софт будет выбирать рандомный