#-------------------------------------------------------GENERAL---------------------------------------------------------

# Ждать заполнения реф. кодов в accounts_data.xlsx
RANGER_WAIT_REFCODE = true

# Пауза между трейдами в секундах [мин, макс] сек.
RANGER_TRADE_SLEEP = [300.0, 600.0]

#---------------------------------------------------------SPOT----------------------------------------------------------

# Диапазон суммы для первой покупки токенов на споте за SOL или USDC.
# Можно указать как в % так и в конкретном значении токена
RANGER_FIRST_SWAP_AMOUNT = ["85", "95"]

# Диапазон процентов для последующих свапов в цикле (smart swaps).
# Указывается в процентах, чтобы можно было обменивать не 100% токена.
# Для меньшей сибильности можно обменивать не весь объём — так процесс выглядит естественнее.
# После завершения цикла свапов автоматически запускается коллектор в SOL/USDC.
RANGER_SWAP_AMOUNT = ["80", "90"]

# Количество свапов в цикле smart swaps. Рандомное значение из диапазона.
RANGER_SMART_SWAPS_COUNT = [45, 50]

# Доступные для свапов токены внутри Ranger
# Чем можно дополнить список: "TRUMP", "JUP", "PENGU", "WIF", "WBTC", "JLP", "Fartcoin", "RAY", "cbBTC", "JITOSOL"
RANGER_AVAILABLE_TOKENS = ["USDC", "USDT"]

# Максимальное проскальзывание в процентах для свапов
RANGER_SLIPPAGE = 0.05

# Каких провайдеров котировок разрешать
# Допустимые значения: "Jupiter", "OKX DEX", "DFlow", "Pyth"
RANGER_QUOTE_PROVIDERS = ["Jupiter", "DFlow"]

# Токены из которых нужно сделать первый свап для инициализации круговых свапов между RANGER_AVAILABLE_TOKENS
RANGER_INITIAL_TOKENS = ["SOL", "USDC"]

# Целевой токен для сбора после свапов. Допустимо: "SOL" или "USDC"
RANGER_COLLECT_TO = "USDC"

# Выполнять сбор токенов в целевой перед началом smart swaps
RANGER_COLLECT_BEFORE = true

# Минимальная USD стоимость токена для smart swap и коллектора
# Токены с балансом меньше этого значения будут игнорироваться при выборе для свапа
RANGER_MIN_USD_FOR_SWAP = 0.5

#--------------------------------------------------------BRIDGE---------------------------------------------------------

# Диапазон сумм USDC для бриджа через Relay
RANGER_BRIDGE_USDC_AMOUNT = ["100", "100"]

# Диапазон сумм ETH для бриджа через Relay
RANGER_BRIDGE_ETH_AMOUNT = [0.001, 0.002]

# Сколько оставить токена на кошельке при бридже из Solana обратно в L2 сети
RANGER_BRIDGE_OUT_LIMITTER = [0.0, 0.0]

#---------------------------------------------------------CEX-----------------------------------------------------------

# Диапазон сумм USDC для вывода с CEX
RANGER_CEX_WITHDRAW_USDC_AMOUNT = [500, 1000]

# Диапазон сумм ETH для вывода с CEX
RANGER_CEX_WITHDRAW_ETH_AMOUNT = [0.0022, 0.0032]

# Диапазон сумм SOL для вывода с CEX
RANGER_CEX_WITHDRAW_SOL_AMOUNT = [0.05, 0.1]

# Диапазон сумм USDC для депозита на CEX
RANGER_CEX_DEPOSIT_USDC_AMOUNT = ["100", "100"]

# Диапазон сумм ETH для депозита на CEX
RANGER_CEX_DEPOSIT_ETH_AMOUNT = ["100", "100"]

# Диапазон сумм SOL для депозита на CEX
RANGER_CEX_DEPOSIT_SOL_AMOUNT = ["100", "100"]

# Сколько оставить на балансе в сети при депозите USDC на CEX
RANGER_CEX_DEPOSIT_USDC_LIMITER = [0.0, 0.0]

# Сколько оставить на балансе в сети при депозите ETH на CEX
RANGER_CEX_DEPOSIT_ETH_LIMITER = [0.0, 0.0]

# Сколько оставить SOL на балансе при депозите на CEX
RANGER_CEX_DEPOSIT_SOL_LIMITER = [0.0, 0.0]

#---------------------------------------------------------PERP----------------------------------------------------------

# Задержка между открытием позиций на разных аккаунтах в секундах [мин, макс]
RANGER_DN_ACCOUNTS_SLEEP_TIME = [60, 90]

# Время удержания delta-neutral позиций в секундах [мин, макс]
# Например [300, 600] = держать позиции 5-10 минут перед закрытием
RANGER_DN_HOLD_TIME = [300, 600]

# Пауза между циклами delta-neutral в секундах [мин, макс]
# Например [1800, 3600] = пауза 30-60 минут между циклами
RANGER_DN_CYCLE_SLEEP_TIME = [1000, 2000]

# Доступные рынки для delta-neutral стратегии
# Поддерживаются: "BTC", "ETH"
RANGER_DN_MARKETS = ["BTC", "ETH"]

# Диапазон кредитного плеча для позиций [мин, макс]
# Рекомендуется 15-30x для оптимального соотношения риск/объем
# Чем выше плечо - тем больше notional объем, но выше риск ликвидации
RANGER_DN_LEVERAGE = [15, 20]

# Количество delta-neutral циклов для выполнения [мин, макс]
# Каждый цикл: открытие позиций → удержание → закрытие → пауза
RANGER_DN_CYCLES_COUNT = [5, 10]

#--------------------------------------------------AVAILABLE MODULES----------------------------------------------------

#  ranger_smart_swaps              # Умные свапы на Ranger Spot. Работает по настройкам SPOT

#  ranger_perp_delta_neutral       # Delta-Neutral стратегия на Perp (работает с 3 аккаунтами)
#  ranger_perp_close_positions     # Принудительное закрытие всех позиций на Perp (работает с 3 аккаунтами)

#  ranger_bridge_usdc_in           # Бридж USDC из L2 сетей в Solana через Relay. Сумма по RANGER_BRIDGE_USDC_AMOUNT
#  ranger_bridge_usdc_out          # Бридж USDC из Solana обратно в L2 сети через Relay. Сумма по RANGER_BRIDGE_USDC_AMOUNT
#  ranger_bridge_eth_in            # Бридж ETH из L2 сетей в Solana через Relay. Сумма по RANGER_BRIDGE_ETH_AMOUNT
#  ranger_bridge_eth_out           # Бридж ETH из Solana обратно в L2 сети через Relay. Сумма по RANGER_BRIDGE_ETH_AMOUNT

#  ranger_cex_withdraw_usdc        # Вывод USDC с CEX на кошельки. Сумма по RANGER_CEX_WITHDRAW_USDC_AMOUNT
#  ranger_cex_withdraw_eth         # Вывод ETH с CEX на кошельки. Сумма по RANGER_CEX_WITHDRAW_ETH_AMOUNT
#  ranger_cex_deposit_usdc         # Депозит USDC с кошельков на CEX. Сумма по RANGER_CEX_DEPOSIT_USDC_AMOUNT
#  ranger_cex_deposit_eth          # Депозит ETH с кошельков на CEX. Сумма по RANGER_CEX_DEPOSIT_ETH_AMOUNT

#  ranger_perp_cex_withdraw_sol    # Вывод SOL с CEX для Perp операций. Сумма по RANGER_CEX_WITHDRAW_SOL_AMOUNT
#  ranger_perp_cex_withdraw_usdc   # Вывод USDC с CEX для Perp операций. Сумма по RANGER_CEX_WITHDRAW_USDC_AMOUNT
#  ranger_perp_cex_deposit_sol     # Депозит SOL на CEX после Perp операций. Сумма по RANGER_CEX_DEPOSIT_AMOUNT_SOL
#  ranger_perp_cex_deposit_usdc    # Депозит USDC на CEX после Perp операций. Сумма по RANGER_CEX_DEPOSIT_AMOUNT_USDC