#----------------------------------------------------REDDIO CONTROL-----------------------------------------------------

REDDIO_ENABLE_BRIDGE_TASK = false  # Выполнять ли ежедневное задание с бриджом?
# Требуется баланс в Sepolia. Если баланса нет, будет выполнен TestnetBridge  
# и, при необходимости, пополнение L2 с биржи. Настройте вывод с биржи и параметры ниже.  

REDDIO_FAUCET_MIN_AMOUNT = [1.0, 1.5] # минимальный баланс токенов RED для пропуска крана при REDDIO_UNLIMIT_FAUCET = false
REDDIO_TRANSFER_AMOUNT = ['1', '10'] # сумма трансферов ETH

REDDIO_TESTNET_BRIDGE_MIN_AMOUNT = 0.05 # минимальное количество ETH в сети Sepolia, чтобы софт запустил бридж из Reddio, иначе будет додеп в Sepolia
REDDIO_TESTNET_BRIDGE_AMOUNT = [0.0001, 0.0002] # сумма бриджа из L2(Arbitrum или Optimism) в Sepolia (минимум, максимум) (% или кол-во)
REDDIO_BRIDGE_AMOUNT = ['1', '2'] # сумма бриджа ETH Sepolia -> RED Reddio
REDDIO_BRIDGE_CHANCE = 100 # Шанс выполнения задания с бриджем
REDDIO_TESTNET_BRIDGE_FEE_SUPPORT = [0.000025, 0.000025] # сумма нативки удержания нативки под комиссию для бриджа через TestnetBridge

REDDIO_WAIT_FOR_VERIFY_TIME = 3600 # Сколько секунд ожидать верификации всех выполненных заданий

REDDIO_TRANSFER_TO_SELF = false 
# Делать ли трансфер RED себе на кошелек для ежедневного задания,
# если false, то сделает трансфер на рандомный адрес
