REDDIO_ENABLE_BRIDGE_TASK = false  # Выполнять ли ежедневное задание с бриджом?
# Требуется баланс в Sepolia. Если баланса нет, будет выполнен TestnetBridge  
# и, при необходимости, пополнение L2 с биржи. Настройте вывод с биржи и параметры ниже.  

REDDIO_TESTNET_BRIDGE_MIN_AMOUNT = 0.05 # минимальное количество ETH в сети Sepolia, чтобы софт запустил бридж из Reddio, иначе будет додеп в Sepolia
REDDIO_TESTNET_BRIDGE_AMOUNT = [0.0001, 0.0002] # сумма бриджа из L2(Arbitrum или Optimism) в Sepolia (минимум, максимум) (% или кол-во)

REDDIO_TESTNET_BRIDGE_FEE_SUPPORT = [0.000025, 0.000025] # сумма нативки удержания нативки под комиссию для бриджа через TestnetBridge
