SAHARA_TRANSFER_AMOUNT = [0.00001, 0.00002] # сумма SAH для трансфера на рандомный кошелек
SAHARA_LOGIN_VIA_REF_CODE = true # поставьте true, чтобы использовать реферральный код для авторизации на сайте
SAHARA_PROCESS_ONCHAIN = true # поставьте true, чтобы проходить ончейн задания
SAHARA_FAUCET_UNLIMITED = true # использовать кран при любом балансе на аккаунте, не забудьте вставить ключ в генеральные настройки

SAHARA_TRANSFER_SAH_AMOUNT = [0.005, 0.006] # сумма для транфера SAH в сети Sahara на кошелек из EVM Deposit Address
SAHARA_TRANSFER_ETH_AMOUNT = ['100', '100'] # сумма для транфера ETH в сети Ethereum на кошелек из EVM Deposit Address

GALXE_AUTO_REFUEL = true # при нехватке $G токенов в Gravity чейне, во время клейма поинтов, софт автоматически запустит рефьюл по настройкам ниже
CLAIM_ONCHAIN_POINTS_REWARDS = false # клеймить ончейн G поинты за выполненные задания на Galxe
GALXE_G_WITHDRAW_AMOUNT = [5, 10] # сумма G для вывода в сеть Gravity из биржи. CEX_USING в settings.toml для указания с какой биржи воркать
GALXE_MIN_G_BALANCE = 5 # минимальный баланс, ниже которого софт запусти вывод из биржи

#-------------------------------------------------------GASZIP----------------------------------------------------------

REFUEL_AUTO_ENABLE = false # включать рефьюл через Gas.Zip при отсутствии баланса в сети Sahara
REFUEL_GASZIP_L2_NETWORK = ['Arbitrum', 'Optimism'] # сети, которые используются для бриджа через рефьюла через Gas.Zip
REFUEL_GASZIP_AMOUNT = [0.0001, 0.0002]        # сумма рефьюла через Gas.Zip