SOMNIA_FAUCET_WAIT_TIME = [181, 240] # Время ожидания (в секундах) после запроса к Somnia Faucet для проверки изменения баланса STT

#----------------------------------------------------Sharing is Caring-----------------------------------------------------
# https://quest.somnia.network/campaigns/7

SOMNIA_STT_TRANSFER_AMOUNT = ["10", "30"] # сумма STT для трансфера самому себе
