# Попробовать автоматически докинуть газ через smart refuel, если его не хватает в Base (true — да, false — просто выдать ошибку)
# Если true, то обязательно настрой:
# - BRIDGE_L2_NETWORKS — список сетей, откуда брать газ (например: ["Arbitrum", "Optimism"])
# - BRIDGE_AMOUNT — примерный объём газа, который нужно перекинуть ~ 0.0015 ETH
# - REFUEL_DAPP — 1 (GasZip. MeMeBridge не поддерживается для этого роута)
# - CEX_USING — ID биржи, если будет задействован вывод, при недостаточном балансе
SOMNIA_SMART_REFUEL = true # запускать рефьел $SOMI из L2, если нехватает нативки в чейне

SOMNIA_ONLY_VERIFY = false # если поставить true, то софт будет пытаться только заверифать квест, без его выполнения

SOMNIA_MEME_TOKENS = [
    "0x3352cc522daea6c2b26139240130568803f34b0b",
    "0x4163c19558875501e5d872b522d41f598367913b",
    "0xce93cfd14228ac08265e3d2a7307efe2e46a7798",
    "0xeb296155a3cd17b5653ee088ba5917442e576b65",
    "0xdb6a8afa240fcb67ffe7a8fd3fcbdf2eee08f152",
    "0xcd2208fc9dac4006a93cff6a74ff713df9535794",
    "0xbe97cc43442ed205390d9d8b75ac77b85225bc39",
] # токены для покупки на https://somnia.meme

SOMNIA_SWAP_AMOUNT = ['10', '15'] # сумма свапов на любых дапках

# Нужно ли проходить необязательные квесты?
SOMNIA_PROCESS_NONMANDATORY_QUESTS = false