SOMNIA_FAUCET_WAIT_TIME = [181, 240] # Время ожидания (в секундах) после запроса к Somnia Faucet для проверки изменения баланса STT

SOMNIA_LINK_TWITTER = true # Автоматически проверяет и привязывает Twitter при авторизации (quest.somnia.network)
SOMNIA_LINK_DISCORD = true # Автоматически проверяет и привязывает Discord при авторизации (quest.somnia.network)

#----------------------------------------------------Sharing is Caring-----------------------------------------------------
# https://quest.somnia.network/campaigns/7

SOMNIA_STT_TRANSFER_AMOUNT = ["10", "30"] # сумма STT для трансфера самому себе
