SOMNIA_FAUCET_WAIT_TIME = [181, 240] # Время ожидания (в секундах) после запроса к Somnia Faucet для проверки изменения баланса STT

SOMNIA_LINK_TWITTER = false # Автоматически проверяет и привязывает Twitter при авторизации (quest.somnia.network) + включает выполнение Twitter квестов
SOMNIA_LINK_DISCORD = false # Автоматически проверяет и привязывает Discord при авторизации (quest.somnia.network) + включает выполнение Discord квестов

SOMNIA_STT_SWAP_AMOUNT = ["1", "3"] # сумма STT для свапов

SOMNIA_MINT_LIQUIDITY_USDC_AMOUNT = ["80", "95"] # сумма USDC.e для внесения ликвидности

#----------------------------------------------------Sharing is Caring-----------------------------------------------------
# https://quest.somnia.network/campaigns/7

SOMNIA_STT_TRANSFER_AMOUNT = ["10", "30"] # сумма STT для трансфера самому себе

#---------------------------------------------------Bigint Onchain Hunt----------------------------------------------------
#https://quest.somnia.network/campaigns/57

# Если выключить (false), то софт минтит все бейджи подряд — но есть шанс «колодца», если бейдж недоступен.
# Если оставить включённым (true), то будет проверяться возраст кошелька и количество транзакций — но часть бейджей может не пройти проверку.
SOMNIA_BIG_INT_CHECK_STATS = true

#-------------------------------------------------Get Your Shannonland ID--------------------------------------------------
# https://quest.somnia.network/campaigns/45

# Нужно ли выполнять задание минтом Somnia - RubyScore ID (0.0015 ETH в Base)
SOMNIA_RUBYSCORE_ENABLED = false

# Попробовать автоматически докинуть газ через smart refuel, если его не хватает в Base (true — да, false — просто выдать ошибку)
# Если true, то обязательно настрой:
# - BRIDGE_L2_NETWORKS — список сетей, откуда брать газ (например: ["Arbitrum", "Optimism"])
# - BRIDGE_AMOUNT — примерный объём газа, который нужно перекинуть ~ 0.0015 ETH
# - REFUEL_DAPP — 1 (GasZip. MeMeBridge не поддерживается для этого роута)
# - CEX_USING — ID биржи, если будет задействован вывод, при недостаточном балансе

SOMNIA_RUBYSCORE_SMART_REFUEL = false

SOMNIA_ONLY_VERIFY = false # если поставить true, то софт будет пытаться только заверифать квест, без его выполнения