SOMNIA_FAUCET_WAIT_TIME = [181, 240] # Время ожидания (в секундах) после запроса к Somnia Faucet для проверки изменения баланса STT

SOMNIA_LINK_TWITTER = true # Автоматически проверяет и привязывает Twitter при авторизации (quest.somnia.network) + включает выполнение Twitter квестов
SOMNIA_LINK_DISCORD = false # Автоматически проверяет и привязывает Discord при авторизации (quest.somnia.network) + включает выполнение Discord квестов

SOMNIA_STT_SWAP_AMOUNT = ["1", "3"] # сумма STT для свапов

#----------------------------------------------------Sharing is Caring-----------------------------------------------------
# https://quest.somnia.network/campaigns/7

SOMNIA_STT_TRANSFER_AMOUNT = ["10", "30"] # сумма STT для трансфера самому себе
