USE_CEX_API = true                            # проверять доступность, минимальную сумму, проверку для депозита на биржи
COLLECT_FROM_SUB_CEX = true                   # собирать средства с суб-аккаунтов
WAIT_FOR_RECEIPT_CEX = true                   # ожидать подтверждения депозита на биржу

SONIC_DEPOSIT_AMOUNT = ['100', '100']         # сумма депозита (% или фиксированное значение)
SONIC_DEPOSIT_FEE = [0.01, 0.02]              # сколько оставить на комиссию в $

SONIC_FTM_WITHDRAW_AMOUNT = [31, 35]          # сумма FTM для вывода в Fantom сеть

SONIC_BEETS_DEPOSIT_AMOUNT = [10, 20]         # сумма sFTMx для депозита на Beets (wFTM/sFTMx pool)
SONIC_MABEETS_DEPOSIT_AMOUNT = [10, 20]       # сумма wFTM для депозита на maBeets
SONIC_MATRIX_DEPOSIT_AMOUNT = [10, 20]        # сумма FTM для депозита на Matrix
