IRYS_SPRITETYPE_GAMES_PER_RUN = [350, 400]       # Сколько игр за одну сессию
IRYS_SPRITETYPE_DURATIONS = [15, 30, 60]             # Какую длительность одной игры задавать. Доступно - 15, 30, 60, 120
IRYS_SPRITETYPE_SLEEP_BETWEEN = [11, 22]         # Время сна между играми


IRYS_SPRITETYPE_CHECK_TOTAL_GAMES = false  # Включить проверку общего количества сыгранных игр на аккаунте; если достигнут лимит, выполнение остановится
IRYS_SPRITETYPE_TOTAL_GAMES = [1010, 1060]  # Целевой диапазон общего количества игр на аккаунте (нижняя и верхняя границы)
