IRYS_SPRITETYPE_GAMES_PER_RUN = [350, 400]       # Сколько игр за одну сессию
IRYS_SPRITETYPE_DURATIONS = [15, 30, 60]             # Какую длительность одной игры задавать. Доступно - 15, 30, 60, 120
IRYS_SPRITETYPE_SLEEP_BETWEEN = [11, 22]         # Время сна между играми


IRYS_SPRITETYPE_TOTAL_GAMES =  [1010, 1060]       # Сколько всего игр набить на аккаунте