STORYHUNT_IP_SWAP_AMOUNT = ["10", "20"]
STORYHUNT_TOKEN_SWAP_AMOUNT = ["48", "52"]

PIPERX_IP_SWAP_AMOUNT = ["10", "20"]
PIPERX_TOKEN_SWAP_AMOUNT = ["48", "52"]

PIPERX_LIQUIDITY_AMOUNT = ["48", "52"]

VERIO_STAKE_AMOUNT = [0.1, 0.2]  # Minimum 0.1 IP

UNLEASH_LOOP_SUPPLY_USDT_AMOUNT = ["20", "30"]
UNLEASH_LOOP_SUPPLY_USDC_AMOUNT = ["20", "30"]

#----------------------------------------------------STORYHUNT BADGE----------------------------------------------------

STORY_STORYHUNT_WIP_TO_SHUSDC_SWAP_AMOUNT = ["1", "2"]
STORY_STORYHUNT_SHUSDC_TO_FATE_SWAP_AMOUNT = ["1", "2"]
STORY_STORYHUNT_WIP_TO_FATE_SWAP_AMOUNT = ["1", "2"]

STORY_WRAP_IP_AMOUNT = ["10", "20"]

