XTERIO_CEX_USING = 3 # биржа через которую будет осуществлен вывод BNB в BSC сеть. 1 - OKX, 3 - Binance, 4 - Bitget
XTERIO_WITHDRAW_BNB_AMOUNT = [0.0014, 0.0015] # сумма для вывода из биржи
XTERIO_BRIDGE_AMOUNT = [0.0002, 0.0003] # сумма для бриджа из BNB Chain -> Xterio

XTERIO_ALLOWED_MISSION = [6, 15, 16, 18, 22, 28]  # разрешенные миссии для отработки, софт будет перебирать миссии, пока не найдет одну из указанных. 0 - любая миссия
XTERIO_AUTISM_MODE = false  # выключает использование GPT и берет фразы для ответов из data/services/simple_answers.txt