PIPERX_USDC_USDT_LIQUIDITY_AMOUNT = ["100", "100"]

CLASSIC_ROUTES_BLOCKS_COUNT = [1, 1]


CLASSIC_ROUTES_MODULES_USING = [
    ["piperx_swap_ip_to_usdc"],
    ["piperx_swap_ip_to_usdt"],
    ["piperx_add_usdc_usdt_liquidity"],
]
