CLASSIC_ROUTES_BLOCKS_COUNT = [2, 2]

CLASSIC_ROUTES_MODULES_USING = [
    ["story_wrap_native"],
    [
        ["story_storyhunt_swap_wip_to_shusdc"],
        ["story_storyhunt_swap_shusdc_to_fate"],
    ],
    [
        ["story_storyhunt_swap_wip_to_fate"],
    ],
]
