WITHOUT_GALXY_UNLINKING = true
CLASSIC_ROUTES_BLOCKS_COUNT = [3, 5]

CLASSIC_ROUTES_MODULES_USING = [
    ["story_unleash_faucet_usdt"],
    [
        ["story_deploy_erc20_contract"],
    ],
    [
        ["story_deploy_basic_contract"],
    ],
    [
        ["story_piperx_swap_ip_to_usdc"],
        ["story_piperx_swap_ip_to_usdt"],
        ["story_piperx_add_usdc_usdt_liquidity"],
    ],
    [
        ["story_verio_stake"],
        ["story_verio_unstake"],
    ],
    [
        ["story_piperx_swap_ip_to_usdt"],
        ["story_unleash_loop_supply_usdt"],
    ],
]
