CLASSIC_ROUTES_BLOCKS_COUNT = [9, 9]

CLASSIC_ROUTES_MODULES_USING = [
    ["storybadge_claim_faucet"],
    [
        ["storybadge_d3x_claim_test_usdt"],
        ["storybadge_d3x_open_trade"],
        ["storybadge_d3x_deposit_test_usdt"],
        ["storybadge_d3x_subscribe"],
        ["storybadge_d3x_mint_badge"],
    ],
    [
        ["storybadge_impossible_finance_mint_tidia_token"],
        ["storybadge_impossible_finance_stake_tidia_token"],
        ["storybadge_impossible_finance_mint_badge"],
    ],
    [
        ["storybadge_playarts_mint_badge"]
    ],
    [
        ["storybadge_poster_mint_badge"]
    ],
    [
        ["storybadge_satori_execute_deposit"],
        ["storybadge_satori_execute_open_trade"],
        ["storybadge_satori_deposit_to_vault"],
        ["storybadge_satori_mint_badge"]
    ],
    [
        ["storybadge_solo_mint_badge"]
    ],
    [
        ["storybadge_storyhunt_mint_badge"]
    ],
    [
        ["storybadge_styreal_mint_badge"]
    ],
    [
        ["storybadge_wand_deposit_to_vault"],
        ["storybadge_wand_mint_badge"],
    ],
]
