CLASSIC_ROUTES_BLOCKS_COUNT = [1, 1]

CLASSIC_ROUTES_MODULES_USING = [
    ["soneium_cex_withdraw_eth"],
    ["soneium_bridge_relay_into"],
    ["soneium_process_all_campaigns"],
    ["soneium_bridge_relay_from"],
    ["soneium_cex_deposit_eth"],
]