CLASSIC_ROUTES_BLOCKS_COUNT = [3, 3]

CLASSIC_ROUTES_MODULES_USING = [
    [
        ["soneium_sonus_claim_badge"]
    ],
    [
        ["soneium_orbiter_claim_badge"]
    ],
    [
        ["soneium_owlto_claim_badge"]
    ],
]
