CLASSIC_ROUTES_BLOCKS_COUNT = [4, 4]


CLASSIC_ROUTES_MODULES_USING = [
    [
        ["soneium_process_owlto_badge"]
    ],
    [
        ["soneium_process_sonus_badge"],
    ],
    [
        ["soneium_process_quick_swap_badge"],
    ],
    [
        ["soneium_process_untitled_bank_badge"],
    ],
]
