CLASSIC_ROUTES_BLOCKS_COUNT = [1, 3]

CLASSIC_ROUTES_MODULES_USING = [
    [
        ['pumpfun_pumpswap_swap_sol_to_usdc'],
        ['pumpfun_pumpswap_swap_usdc_to_sol'],
    ],
    [
        ['pumpfun_pumpswap_swap_sol_to_apt'],
        ['pumpfun_pumpswap_swap_apt_to_sol'],
    ],
    [
        ['pumpfun_pumpswap_swap_sol_to_pengu'],
        ['pumpfun_pumpswap_swap_pengu_to_sol'],
    ],
]