CLASSIC_ROUTES_MODULES_USING = [
    ['eclipse_export_invite_code'],
]

CLASSIC_ROUTES_BLOCKS_COUNT = [1,1]

CLASSIC_ROUTES_MODULES_USING = [
    ['withdraw_eth_to_l2'],
    ['bridge_eth_to_sol_jumper'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_refuel_gazzip'],
    ['eclipse_swap_sol_to_eth_orca'],
    [
        ['eclipse_swap_eth_to_usdc_solar'],
        ['eclipse_swap_usdc_to_eth_solar'],
    ],
    [
        ['eclipse_swap_eth_to_sol_orca'],
        ['eclipse_swap_sol_to_eth_orca']
    ],
    [
        ['eclipse_swap_eth_to_usdc_orca'],
        ['eclipse_swap_usdc_to_eth_orca']
    ],
    ['eclipse_cex_withdraw_sol'],
    ['eclipse_bridge_sol_usenexus'],
    ['eclipse_refuel_gazzip'],
    ['eclipse_swap_sol_to_eth_orca'],
    [
        ['eclipse_swap_eth_to_usdc_solar'],
        ['eclipse_swap_usdc_to_eth_solar'],
    ],
    [
        ['eclipse_swap_eth_to_sol_orca'],
        ['eclipse_swap_sol_to_eth_orca']
    ],
    [
        ['eclipse_swap_eth_to_usdc_orca'],
        ['eclipse_swap_usdc_to_eth_orca']
    ],
]