CLASSIC_ROUTES_BLOCKS_COUNT = [2, 2]

CLASSIC_ROUTES_MODULES_USING = [
    ["ink_mint_ink_the_future_nft"],
    ["ink_mint_superchain_nft"],
    ["ink_mint_domain_zns"],
    ["ink_stake_dinero"],
    ["ink_process_wrap_task"],
    ["ink_process_twitter_tasks"],
    [
        ["ink_velodrome_swap_eth_to_usdc"],
        ["ink_deposit_usdc_the_deep"],
    ],
]
