CLASSIC_ROUTES_MODULES_USING = [
    ['unisat_pizzaswap_deposit'],
    ['unisat_pizzaswap_swap'],
    ['unisat_pizzaswap_add_liquidity'],
    ['unisat_pizzaswap_stake_liquidity'],
]

UNISAT_PIZZA_SWAP_TOKENS_FROM = ["sFB"]                # Токены из которых будет сделан свап (будет выбран случайный)
UNISAT_PIZZA_SWAP_TOKENS_TO = ["sBTC"]                 # Токены в которые будет сделан свап (будет выбран случайный)
UNISAT_PIZZA_SWAP_AMOUNT = ["50", "55"]              # Сумма свапа в количестве или в процентах

UNISAT_PIZZA_SWAP_LIQUIDITY_TOKENS = ["sFB", "sBTC"]   # Токены для добавления/вывода ликвидности (будут взяты по очереди).
UNISAT_PIZZA_SWAP_LIQUIDITY_AMOUNT = ["98", "98"]      # Сумма для добавления ликвидности в количестве или в процентах

UNISAT_PIZZA_SWAP_SLIPPAGE = 5                         # Максимальное проскальзывание в процентах

UNISAT_PIZZA_SWAP_DEPOSIT_TOKENS = ["FB"]             # Токены для которых будет сделан депозит (будет выбран случайный)
UNISAT_PIZZA_SWAP_WITHDRAW_TOKENS = ["sFB"]            # Токены для которых будет сделан вывод (будет выбран случайный)

UNISAT_PIZZA_SWAP_FEE_TOKEN = "sFB"                    # Токен в котором будет происходить оплата комиссий (поддерживаются bFB, sFB, bSATS, sSATS)
