#-------------------------------------------------CLASSIC-ROUTES CONTROL-------------------------------------------------

#--------------------------------------------------------HELPERS---------------------------------------------------------

#    okx_withdraw                     # смотри CEX CONTROL
#    binance_withdraw                 # смотри CEX CONTROL
#    bitget_withdraw                  # смотри CEX CONTROL

#    create_order_on_ff               # создание ордера на https://ff.io/. см. FIXEDFLOAT

#    okx_deposit                      # ввод средств на биржу + сбор средств на субАккаунтов на основной счет
#    binance_deposit                  # ввод средств на биржу + сбор средств на субАккаунтов на основной счет
#    bitget_deposit                   # ввод средств на биржу + сбор средств на субАккаунтов на основной счет

#--------------------------------------------------------UNISAT----------------------------------------------------------

#    inscribe_brc_20                  # минт инскрипции на https://unisat.io/inscribe. см. INSCRIPTIONS
#    make_inscription_transferable    # делает инскрипцию продаваемой см. TRANSFERABLE_INSCRIPTIONS
#    list_inscription                 # создание ордера на продажу инскрипции см. LIST_INSCRIPTIONS
#    delist_inscription               # удаление ордера на продажу инскрипции см. DELIST_INSCRIPTIONS
#    deploy_brc_20                    # деплой инскрипции на https://unisat.io/inscribe. см. INSCRIPTIONS
#    mint_rune                        # минт рун на https://unisat.io/runes/inscribe. см. RUNES
#    list_rune                        # создание ордера на продажу руны см. LIST_RUNES
#    delist_rune                      # удаление ордера на продажу руны см. DELIST_RUNES
#    deploy_rune                      # деплой рун на https://unisat.io/runes/inscribe. см. RUNES
#    deploy_and_inscribe_brc20_5byte  # деплой и минт 5 байтной инскрипции. см. INSCRIPTIONS
#    bridge_btc_to_sbtc               # бридж BTC -> sBTC в сети BRC. см. BTC_SBTC_BRIDGE_AMOUNT
#    bridge_sbtc_to_btc               # бридж sBTC -> BTC в сети BRC. см. BTC_SBTC_BRIDGE_AMOUNT
#
#--------------------------------------------------------FRACTAL---------------------------------------------------------
#    custom_transfer                  # трансфер токенов на адрес, указанный в поле 'OKX BTC address'. см. CUSTOM_TRANSFER_DATA
#    faucet_infinity_fractal          # клейм $FB на сайте https://app.infinityai.network/
#    faucet_opnet_fractal             # клейм $FB на сайте https://fractal-faucet.opnet.org/
#    faucet_fractal                   # клейм $FB на сайте https://explorer.fractalbitcoin.io/faucet
#    check_in_infinity                # checkIn на сайте https://app.infinityai.network/
#    inscribe_brc_20_fractal_testnet  # минт инскрипции на https://fractal-testnet.unisat.io/inscribe. см. INSCRIPTIONS
#    inscribe_brc_20_fractal          # минт инскрипции на https://fractal.unisat.io/inscribe. см. INSCRIPTIONS
#    deploy_brc_20_fractal_testnet    # деплой инскрипции на https://fractal-testnet.unisat.io/inscribe. см. INSCRIPTIONS
#    deploy_brc_20_fractal            # деплой инскрипции на https://fractal.unisat.io/inscribe. см. INSCRIPTIONS
#    mint_rune_fractal                # минт рун на https://fractal.unisat.io/runes. см. RUNES
#    deploy_rune_fractal              # деплой руны Fractal на https://fractal.unisat.io/inscribe.
#    make_inscription_transferable_fractal  # делает инскрипцию продаваемой Fractal см. TRANSFERABLE_INSCRIPTIONS_FRACTAL
#    list_inscription_fractal         # создание ордера на продажу инскрипции Fractal см. LIST_INSCRIPTIONS_FRACTAL
#    delist_inscription_fractal       # удаление ордера на продажу инскрипции см. DELIST_INSCRIPTIONS_FRACTAL
#    list_rune_fractal                # создание ордера на продажу руны Fractal см. LIST_RUNES_FRACTAL
#    delist_rune_fractal              # удаление ордера на продажу руны Fractal см. DELIST_RUNES_FRACTAL
#    bridge_fb_to_sfb_fractal         # бридж FB -> sFB в сети Fractal. см. FB_SFB_BRIDGE_AMOUNT
#    bridge_sfb_to_fb_fractal         # бридж sFB -> FB в сети Fractal. см. FB_SFB_BRIDGE_AMOUNT
#
#------------------------------------------------------------------------------------------------------------------------
#
#    Выберите необходимые модули для взаимодействия
#    Вы можете создать любой маршрут, софт отработает строго по нему. Для каждого списка будет выбран один модуль в
#    маршрут, если софт выберет None, то он пропустит данный список модулей.
#    Список модулей сверху.

#    CLASSIC_ROUTES_MODULES_USING = [
#        ['okx_withdraw'],
#        ['inscribe_brc_20', 'deploy_brc_20'],
#        ['mint_rune', 'deploy_rune'],
#        ...
#    ]

CLASSIC_ROUTES_BLOCKS_COUNT = [2, 2]  # Количество блоков к работе для одного аккаунта.

CLASSIC_ROUTES_MODULES_USING = [
    # при наличии блоков (круглые скобки для маршрута), софт будет их мешать для каждого аккаунта
    ['deploy_rune'],
     # ['inscribe_brc_20'],
     # ['deploy_brc_20'],
    # ['mint_rune'],
    # ['deploy_rune'],
]