CLASSIC_ROUTES_MODULES_USING = [
    ['unisat_inscribe_brc_20', 'unisat_inscribe_brc_20_fractal', "None"],
    ['unisat_deploy_brc_20', 'unisat_deploy_brc_20_fractal', "None"],
    ['unisat_mint_rune', 'unisat_mint_rune_fractal', "None", "None", "None"],
    ['unisat_deploy_rune', 'unisat_deploy_rune_fractal'],
    ['unisat_deploy_and_inscribe_brc20_5byte', 'unisat_inscribe_brc_20_fractal', "None", "None"],
    ['unisat_deploy_brc_20', 'unisat_deploy_rune', 'unisat_inscribe_brc_20_fractal'],
    ['unisat_mint_rune', 'unisat_deploy_and_inscribe_brc20_5byte', 'unisat_deploy_rune_fractal', "None"],
    ['unisat_deploy_rune_fractal', 'unisat_deploy_brc_20', "None", "None"],
    ['unisat_inscribe_brc_20', 'unisat_deploy_rune_fractal', 'unisat_mint_rune_fractal'],
    ['unisat_deploy_and_inscribe_brc20_5byte', 'unisat_deploy_brc_20_fractal'],
    ['unisat_mint_rune_fractal', 'unisat_inscribe_brc_20'],
    ['unisat_deploy_rune', 'unisat_deploy_rune_fractal', "None", "None", "None"],
    ['unisat_inscribe_brc_20', 'unisat_mint_rune', 'unisat_inscribe_brc_20_fractal'],
    ['unisat_deploy_brc_20', 'unisat_mint_rune_fractal'],
]