CLASSIC_ROUTES_BLOCKS_COUNT = [3, 3]

CLASSIC_ROUTES_MODULES_USING = [
    [
        ["abstract_deposit_zerolend"],
        ["abstract_withdraw_zerolend"]
    ],
    [
        ["abstract_mint_nfts2me"]
    ],
    [
        ["abstract_full_swaps_zoofun"]
    ],
]